#!/usr/bin/env node
/**
 * Writes the current offer-banner URLs into index.html so a first-ever visit
 * paints the carousel from the HTML instead of waiting for /api/site-media.
 *
 *   node tools/snapshot-banners.mjs            # read from the live site
 *   node tools/snapshot-banners.mjs --from-render   # skip the edge, ask Render
 *   node tools/snapshot-banners.mjs --check    # exit 1 if the snapshot is stale
 *   node tools/snapshot-banners.mjs --url=...  # read from somewhere else
 *
 * Run it whenever the offer banners change, before deploying. The snapshot is
 * a starting picture, not a source of truth: site-media.js still fetches the
 * live map on every load and re-renders if it differs, so a stale snapshot
 * costs a swap on first paint, never a wrong banner for the whole session.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const INDEX = join(ROOT, 'index.html');

const EDGE = 'https://ozylix.com/api/site-media';
const RENDER = 'https://ascovitahealthcare-cell-github-io.onrender.com/api/site-media';
const START = '<!-- OZYLIX:BANNER-SNAPSHOT:START -->';
const END = '<!-- OZYLIX:BANNER-SNAPSHOT:END -->';
const MAX_BANNERS = 9; // matches the loop in scripts/site-media.js

const argv = process.argv.slice(2);
const args = new Set(argv);
const check = args.has('--check');
const urlArg = (argv.find(a => a.startsWith('--url=')) || '').slice('--url='.length);

// Mirrors cdnImg() in scripts/store-core.js: a public Supabase storage URL is
// served through the Worker's edge cache at /cdn-storage/<bucket>/<path>. The
// preload has to name the URL the carousel will actually request, or it is a
// second download that helps nothing. Keep in step with store-core.
function cdnImg(url) {
  if (!url) return url;
  const m = String(url).match(/^https?:\/\/[^/]+\/storage\/v1\/object\/public\/([^"'?\s]+)(\?.*)?$/);
  return m ? '/cdn-storage/' + m[1] + (m[2] || '') : String(url);
}

// Only these keys are inlined. The full media map is several KB of URLs the
// first paint does not need; the banners are the only part that is visible
// above the fold before the API answers.
function bannerKeys(map) {
  const out = {};
  for (let i = 1; i <= MAX_BANNERS; i++) {
    const url = map['home.banner.' + i];
    if (!url) continue;
    out['home.banner.' + i] = url;
    for (const suffix of ['.alt', '.link']) {
      const k = 'home.banner.' + i + suffix;
      if (map[k]) out[k] = map[k];
    }
  }
  return out;
}

async function fetchMap() {
  const urls = urlArg ? [urlArg] : args.has('--from-render') ? [RENDER] : [EDGE, RENDER];
  let lastErr;
  for (const url of urls) {
    try {
      const r = await fetch(url, { headers: { Accept: 'application/json' } });
      if (!r.ok) throw new Error('HTTP ' + r.status);
      const body = await r.json();
      const map = body && (body.data || body);
      if (!map || typeof map !== 'object') throw new Error('unexpected payload');
      console.log('· read ' + Object.keys(map).length + ' media keys from ' + url);
      return map;
    } catch (e) {
      lastErr = e;
      console.warn('· ' + url + ' failed: ' + e.message);
    }
  }
  throw lastErr;
}

// The snapshot goes into <head> as data plus one preload for the first slide.
// The preload is the half that actually saves time: it starts the image
// download during HTML parse, well before the deferred scripts run.
function renderBlock(banners) {
  const keys = Object.keys(banners);
  if (!keys.length) {
    return START + '\n  ' + END;
  }
  const first = banners['home.banner.1'] ||
                keys.map(k => banners[k]).find(v => /^https?:/.test(v));
  const lines = [START];
  lines.push('<!-- Generated by tools/snapshot-banners.mjs — do not hand-edit. -->');
  if (first) {
    lines.push('<link rel="preload" as="image" fetchpriority="high" href="' + esc(cdnImg(first)) + '">');
  }
  // The map keeps the canonical URLs; the client runs them through its own
  // cdnImg() exactly as it does for a map fetched from the API.
  lines.push('<script>window.__OZYLIX_BANNER_SNAPSHOT=' + JSON.stringify(banners).replace(/<\//g, '<\\/') + ';<\/script>');
  lines.push(END);
  return lines.join('\n  ');
}

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}

const map = await fetchMap();
const banners = bannerKeys(map);
const count = Object.keys(banners).filter(k => /^home\.banner\.\d+$/.test(k)).length;

const html = readFileSync(INDEX, 'utf8');
const from = html.indexOf(START);
const to = html.indexOf(END);
if (from === -1 || to === -1 || to < from) {
  console.error('Could not find the snapshot markers in index.html. Restore:\n  ' + START + '\n  ' + END);
  process.exit(2);
}

const next = html.slice(0, from) + renderBlock(banners) + html.slice(to + END.length);

if (next === html) {
  console.log('✓ snapshot already current (' + count + ' banner' + (count === 1 ? '' : 's') + ')');
  process.exit(0);
}
if (check) {
  console.error('✗ snapshot is stale — run: node tools/snapshot-banners.mjs');
  process.exit(1);
}

writeFileSync(INDEX, next);
console.log('✓ wrote ' + count + ' banner' + (count === 1 ? '' : 's') + ' into index.html');
